local require = function(filename)
  require("plugin." .. filename)
end

require("which-key")
require("autopairs")
require("diffview")
require("fugitive")
require("fzf")
require("gitsigns")
require("harpoon")
require("marks")
require("matchup")
require("mini")
require("nvim-tree")
require("spectre")
-- require("startify")
require("resession")
require("toggleterm")
require("undotree")
require("nvim-surround")
require("ufo")

require("telescope")
require("lsp")
require("development")
require("appearance")
require("search")
