# Doc: https://alacritty.org/config-alacritty.html
# Example: https://github.com/azigler/dotfiles/blob/main/alacritty/alacritty.toml

[general]
# https://github.com/alacritty/alacritty-theme/tree/master?tab=readme-ov-file#color-schemes
import = ["~/.config/alacritty/themes/themes/catppuccin_mocha.toml"]

[font]
normal = { family = "MonaspiceNe Nerd Font", style = "Regular" }
size = 16.0

[bell]
animation = "Ease"
duration = 300
command = { program = "afplay", args = ["/System/Library/Sounds/Funk.aiff"] }

[window]
opacity = 1
blur = true
dynamic_padding = true
# startup_mode = "SimpleFullscreen"
decorations = "Full"   # "Full" | "None" | "Transparent" | "Buttonless"
dynamic_title = true
option_as_alt = "Both"

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "Off" }

[hints]
[[hints.enabled]]
command = "open" # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"

[mouse]
bindings = [
  { mouse = "Left", mods = "Command", action = "ExpandSelection" },
  { mouse = "Right", action = "Copy" },
]

[keyboard]
# Default bindings: https://alacritty.org/config-alacritty-bindings.html
# - cmd+shift+]/[: SelectNextTab/SelectPreviousTab
bindings = [
  { key = "Enter", mods = "Control | Command", mode = "~Search", action = "ToggleViMode" },
  { key = "Enter", mods = "Control | Command", mode="Vi|~Search", action = "ScrollToBottom" },
  { key = "Enter", mode = "Search", action = "SearchFocusNext" },
  { key = "Enter", mods = "Shift", mode = "Search", action = "SearchFocusPrevious" },
  # { key = "f", mods = "Control | Command", action = "ToggleMaximized" },
  { key = "Enter", mods = "Command", action = "ToggleMaximized" },
  { key = "=", mods = "Command", action = "IncreaseFontSize" },
  { key = "-", mods = "Command", action = "DecreaseFontSize" },
  { key = "0", mods = "Command", action = "ResetFontSize" },
  { key = "ArrowDown", mods = "Shift", action = "ScrollHalfPageDown" },
  { key = "ArrowUp", mods = "Shift", action = "ScrollHalfPageUp" },
]