if empty($XDG_CACHE_HOME)
    let $XDG_CACHE_HOME = '~/.cache'
endif
if empty($XDG_CONFIG_HOME)
    let $XDG_CONFIG_HOME = '~/.config'
endif

set directory=$XDG_CACHE_HOME/vim/swap,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim/backup,~/,/tmp
set undodir=$XDG_CACHE_HOME/vim/undo,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo

" `:set runtimepath?` to list all runtime path in vim
" `vim -V` to show all runtime path at vim starup
" https://thevaluable.dev/vim-runtime-guide-example/
set runtimepath+=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME

" runtime to load vim configuration by relative path
runtime minimal.vim
runtime basic.vim  " OR source $XDG_CONFIG_HOME/vim/basic.vim
if !has('ide')  " if not in ideavim
    runtime plugin.vim
    " runtime extended.vimm
endif
