# https://starship.rs/config
add_newline = true

# continuation_prompt = "[▶▶ ](bold green)"
format = """
$character\
$all\
$fill \
$jobs\
$cmd_duration\
$time\
$memory_usage\
$line_break\
$character
"""

[character]
success_symbol = "[➜](bold green)"
# success_symbol = "[▶](bold green)"
error_symbol = "[✘](bold red)"

[time]
disabled = false
time_format = "%R"
format = '🕒[$time]($style) '

[cmd_duration]
min_time = 1000
format = '[⌛️$duration](green) '

[fill]
# symbol = '─'
symbol = ' '
style = 'fg:#dce0e8'

[directory]
truncation_length = 4
truncate_to_repo = true
truncation_symbol = '…/'

[git_branch]
format = "on [$branch]($style) "

# https://starship.rs/config/#git-status
[git_status]
ahead = "[⏶${count}](bold green)"
behind = "[⏷${count}](bold red)"
diverged = "[⏶${ahead_count}](bold green)[⏷${behind_count}](bold red)"
up_to_date = "[✓](bold green)"
untracked = "[?${count}](bold #EEEEEE)"
modified = "[!${count}](bold fg:#FFF89A)"
staged = "[+${count}](bold fg:#9ADCFF)"
stashed = "[•${count}](bold fg:#A2DBFA)"
renamed = "[»${count}](bold fg:#FFF89A)"
deleted = "[✘${count}](bold fg:#FFF89A)"
# format = '($stashed$untracked$conflicted$deleted$renamed$modified$staged )([\[$ahead_behind\]]($style) )'
format = '(($modified$staged )[\[$ahead_behind\]]($style)) '
style = "bold #bababa"

[git_metrics]
format = '([+$added]($added_style)/[-$deleted]($deleted_style) )'
disabled = true

[git_commit]
disabled = false

[package]
disabled = true

[memory_usage]
threshold = 0
format = "[\\[${ram}\\]]($style)"
disabled = false
# [os]
# disabled = false
