#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# run below command to update configuration
# brew services restart yabai

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.9

yabai -m config window_border                off
yabai -m config window_border_width          6
#yabai -m config active_window_border_color   0xff775759
yabai -m config active_window_border_color   0xff13c236
yabai -m config normal_window_border_color   0xff555555
yabai -m config insert_feedback_color        0xffd75f5f
yabai -m config split_ratio                  0.50

yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0
yabai -m config layout                       float
# yabai -m config --space 2 layout             float

# bar settings
# yabai -m config external_bar all:25:0

# applications exclued from bsp (float mode)
yabai -m rule --add app="^TickTick$" manage=off sticky=on
yabai -m rule --add app="^WeChat$" manage=off sticky=on
yabai -m rule --add app="^Discord$" manage=off sticky=on
yabai -m rule --add app="^Telegram$" manage=off
yabai -m rule --add app="^Hammerspoon$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer" manage=off
yabai -m rule --add app="^Karabiner-Elements" manage=off
yabai -m rule --add app="^YoudaoDict$" manage=off sticky=on
yabai -m rule --add app="^Bitwarden$" manage=off sticky=on
yabai -m rule --add app="^Hidden Bar$" manage=off sticky=on
yabai -m rule --add app="^Dash$" manage=off sticky=on
yabai -m rule --add app="^Alfred" manage=off sticky=on
yabai -m rule --add app="^AltTab" manage=off sticky=on
yabai -m rule --add app="(IntelliJ IDEA|GoLand)" title="Rename|Find|Commit|Copy|Rollback|Preferences|Invalidate|New|Move|Copy|Safe Delete|Tip" manage=off

yabai -m rule --add app="^System Preferences$" manage=off sticky=on
yabai -m rule --add app="^Activity Monitor$" manage=off sticky=on
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^App Store$" manage=off
yabai -m rule --add app="^Dictionary$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add title="Software Update$" manage=off
yabai -m rule --add app="^System Information$" title="About This Mac" manage=off
yabai -m rule --add app="^Script Editor$" manage=off

echo "yabai configuration loaded.."
