# ~/.zshenv is loaded before ~/.zshrc
# and script only loads ~/.zshenv but not ~/.zshrc
#
# zsh configuration loading order
#   https://scriptingosx.com/2019/06/moving-to-zsh-part-2-configuration-files/

# XDG Base Directory
# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# zsh
export ZSH=$XDG_CONFIG_HOME/oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom
export ZSH_THEME=$ZSH/themes

# dotfiles
export DOTFILES_HOME=$HOME/.dotfiles
export DOTFILES_BIN_HOME=$DOTFILES_HOME/bin
export DOTFILES_ZSH_HOME=$DOTFILES_HOME/zsh

export CHEATSHEETS_HOME=$DOTFILES_HOME/cheatsheets
export TMUX_CONF=$HOME/.tmux.conf

# history
export HISTFILE=$XDG_CONFIG_HOME/zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTCONTROL='ignoreboth' # don't show duplicates and commands that begin with a space in history.

# my workspace
export WORKSPACE=$HOME/workspace

# fzf
FZF_BASE_OPTS="--exact --extended --multi --color=16,hl:green,header:bold --ansi --tabstop=4 --info=inline --layout=reverse --cycle \
--bind 'tab:down' \
--bind 'btab:up' \
--bind='ctrl-n:down' \
--bind='ctrl-p:up' \
--bind='ctrl-k:page-down' \
--bind='ctrl-j:page-up' \
--bind 'ctrl-s:toggle' \
--bind='alt-j:preview-down' \
--bind='alt-k:preview-up' \
--bind='alt-d:preview-half-page-down' \
--bind='alt-u:preview-half-page-up' \
--bind 'ctrl-/:toggle-preview' \
--bind 'alt-enter:print-query'"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="$FZF_BASE_OPTS --height=40%"
export CLICOLOR_FORCE=1  # Interpret ANSI color codes from the input (https://github.com/junegunn/fzf/issues/150)

# enable en_US locale with UTF-8 encodings
export LANG=en_US.UTF-8
export LC_ALL=$LANG

# appearance
export TERM="xterm-256color"
export LSCOLORS=ExFxCxDxBxegedabagacad  # for FreeBSD/macOS
export LS_COLORS=${LS_COLORS:-'di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:'}  # for linux (https://github.com/
export ZLS_COLORS=$LS_COLORS
export PAGER='less'
# less color
#   -i: ignore case at search
#   -M: more information in prompt
#   -s: combine multiple blank lines into one line
#   -F: quit if screen can shows all content
#   -R: not show escape sequences like ESC[, and will convert them into ANSI color
#   -j2: lines between top and matched text (https://superuser.com/a/257626)
#   --mouse: enable mouse input
export LESS='-iMsFR -j2 --mouse'
# `less <file>` shows information according to file type
export LESSOPEN='|$DOTFILES_HOME/bin/_lessfilter %s'

if [[ -n $(command -v code) ]]; then
    EDITOR='code'
else
    EDITOR='vim'
fi
export EDITOR

# other environment variables
alias rg='rg -L'
alias exa='exa -Fh --git --time-style=long-iso --sort=name'
alias python=python3
export PYTHONIOENCODING='UTF-8'
if [[ $OSTYPE == 'darwin'* ]]; then
    alias sed=gsed  # make sed compatible with linux version
fi
export NAVI_CONFIG=$DOTFILES_HOME/config/navi_config.yaml
# export NAVI_FZF_OVERRIDES_VAR='--multi'
source $HOME/.cargo/env

# by default CDPATH=.
CDPATH=.:$HOME

# path
export PATH=$DOTFILES_BIN_HOME:$HOME/.local/bin:/usr/local/sbin:$PATH

[[ -e $DOTFILES_ZSH_HOME/zshenv.local ]] && source $DOTFILES_ZSH_HOME/zshenv.local
