# ~/.zshenv is loaded before ~/.zshrc
# and script only loads ~/.zshenv but not ~/.zshrc
#
# zsh configuration loading order
#   https://scriptingosx.com/2019/06/moving-to-zsh-part-2-configuration-files/

# XDG Base Directory
# https://wiki.archlinux.org/title/XDG_Base_Directory
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# zsh
export ZSH=$XDG_CONFIG_HOME/oh-my-zsh
export ZSH_CUSTOM=$ZSH/custom

# dotfiles
export DOTFILES_HOME=$HOME/.dotfiles
export DOTFILES_BIN_HOME=$DOTFILES_HOME/bin
export DOTFILES_ZSH_HOME=$DOTFILES_HOME/zsh

export CHEATSHEETS_HOME=$DOTFILES_HOME/cheatsheets
export TMUX_CONF=$HOME/.tmux.conf

# my workspace
export WORKSPACE=$HOME/workspace
export BLOG_HOME=$WORKSPACE/blog

# https://github.com/ohmyzsh/ohmyzsh/issues/8743
export WORDCHARS=$'!"#$%&\'()*+,-.:;<=>?@[\\]^_`{|}~'

# editor
if [[ -n $(command -v code) ]]; then
    EDITOR='code'
else
    EDITOR='vim'
fi
export EDITOR

# fzf
FZF_BASE_OPTS="--no-sort --extended --multi --color=16,hl:green,header:bold --ansi --tabstop=4 --info=inline --layout=reverse --cycle \
--bind='ctrl-n:down' \
--bind='ctrl-p:up' \
--bind='ctrl-alt-n:page-down' \
--bind='ctrl-alt-p:page-up' \
--bind='alt-a:toggle-all' \
--bind='alt-n:toggle+down' \
--bind='alt-p:toggle+up' \
--bind='ctrl-space:toggle' \
--bind='alt-f:preview-half-page-down' \
--bind='alt-b:preview-half-page-up' \
--bind='shift-up:preview-page-up' \
--bind='shift-down:preview-page-down' \
--bind 'ctrl-\:toggle-preview' \
--bind 'alt-enter:print-query'"
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_DEFAULT_OPTS="$FZF_BASE_OPTS --height=60%"
export CLICOLOR_FORCE=1  # Interpret ANSI color codes from the input (https://github.com/junegunn/fzf/issues/150)

# enable en_US locale with UTF-8 encodings
export LANG=en_US.UTF-8
export LC_ALL=$LANG

# appearance
export TERM="xterm-256color"
export LSCOLORS=ExFxCxDxBxegedabagacad  # for FreeBSD/macOS
export LS_COLORS=${LS_COLORS:-'di=34:ln=35:so=32:pi=33:ex=31:bd=36;01:cd=33;01:su=31;40;07:sg=36;40;07:tw=32;40;07:ow=33;40;07:'}  # for linux (https://github.com/
export ZLS_COLORS=$LS_COLORS
export PAGER='less'
# colorful man
# https://blog.quarticcat.com/posts/how-do-i-make-my-zsh-smooth-as-fuck/#man-pages; export MANPAGER='sh -c "col -bx | bat -pl man --theme=Monokai\ Extended"'
export MANROFFOPT='-c'
# less color
#   -i: ignore case at search
#   -M: more information in prompt
#   -s: combine multiple blank lines into one line
#   -F: quit if screen can shows all content
#   -R: not show escape sequences like ESC[, and will convert them into ANSI color
#   -j2: lines between top and matched text (https://superuser.com/a/257626)
#   --mouse: enable mouse input
export LESS='--tabs 4 -j2 -iMsFR'
# `less <file>` shows information according to file type
export LESSOPEN='|$DOTFILES_HOME/bin/_lessfilter %s'

# path
_set_path() {
    PATH="/opt/homebrew/bin:/usr/local/bin:/usr/local/sbin:$PATH"
    # use homebew gnu command line tools instead of built-in those
    if [[ $OSTYPE == 'darwin'* ]]; then
        local packages=(gnu-tar gnu-which grep gawk gnu-sed findutils coreutils)
        for i in "${packages[@]}"; do
            PATH="$(brew --prefix)/opt/$i/libexec/gnubin:$PATH"
        done
    fi
    PATH="$HOME/.cargo/bin:$PATH"  # bin from third party
    PATH="$DOTFILES_BIN_HOME:$DOTFILES_BIN_HOME/git:$HOME/.local/bin:$PATH"
    export PATH
}
_set_path
CDPATH=.:$HOME  # by default CDPATH=.

# https://news.ycombinator.com/item?id=30483417
unset NO_COLOR

# other environment variables
export PYTHONIOENCODING='UTF-8'
export NAVI_CONFIG_YAML="$(cat $XDG_CONFIG_HOME/navi/config.yaml)"
export NNN_FIFO=/tmp/nnn.fifo
export NNN_PLUG='f:finder;o:fzopen;c:fzcd;d:diffs;i:imgview;p:fzplug;v:preview-tui'

[[ -e $DOTFILES_ZSH_HOME/zshenv.local ]] && source $DOTFILES_ZSH_HOME/zshenv.local
