# prevent > from overwriting existent file
# using >| to write forcedly
set -o noclobber
unsetopt BEEP             # turn off bell/beep
typeset -U PATH           # prevent duplicate path
setopt EXTENDED_GLOB      # extended globbing
DISABLE_AUTO_UPDATE="true" # disable zsh auto update
# skip the verification of insecure directories
# if it doesn't work, try compaudit | xargs chmod g-w,o-w
ZSH_DISABLE_COMPFIX="true"

# history
setopt SHARE_HISTORY        # adds history incrementally and share it across sessions
setopt EXTENDED_HISTORY     # add timestamps to history
setopt HIST_IGNORE_ALL_DUPS # don't record duplicated commands in history
setopt HIST_SAVE_NO_DUPS    # don't save duplicates
setopt HIST_REDUCE_BLANKS   # Remove superfluous blanks from each command line being added to the history list.
setopt HIST_IGNORE_SPACE
setopt HIST_FIND_NO_DUPS
export HISTFILE=$XDG_CONFIG_HOME/zsh_history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTCONTROL='ignoreboth' # don't show duplicates and commands that begin with a space in history.

# directory stack
# ref: https://zsh.sourceforge.io/Intro/intro_6.html
setopt AUTO_CD              # simply type dir name to cd
setopt AUTO_PUSHD           # push the current directory visited on the stack.
setopt PUSHD_IGNORE_DUPS    # do not store duplicates in the stack.
setopt PUSHD_SILENT         # do not print the directory stack after pushd or popd.

# +-----------+
# | plugins   |
# +-----------+
# tmux https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux
source $DOTFILES_ZSH_HOME/appearance.zsh
plugins=(
    autoupdate  # https://github.com/TamCore/autoupdate-oh-my-zsh-plugins
    macos
    autojump
    timer
    # fancy-ctrl-Z
    # colored-man-pages
    alias-tips
    extract
    rust
    zsh-completions
)
source $ZSH/oh-my-zsh.sh
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# +------------+
# | completion |
# +------------+
fpath+=(
    $DOTFILES_ZSH_HOME/completions  # customized zsh completions
)
source $DOTFILES_ZSH_HOME/complete.fzf.zsh

# autoload loads script as function by searching $fpath.
# ref: https://coderwall.com/p/ktv3hq/zsh-autoloading-functions-i
# initialize autocomplete
autoload -U compinit
# -u avoid security check
# -d <dumpfile> specify dump file location
compinit -u
# _gnu_generic can create completions for gnu commands that list option help (when --help is used) in a standardized way.
compdef _gnu_generic fzf curl
source $ZSH_CUSTOM/plugins/fzf-tab/fzf-tab.zsh
source $DOTFILES_ZSH_HOME/complete.zsh
# load plugins by manual
source $ZSH_CUSTOM/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
source $ZSH_CUSTOM/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# +----------------+
# |  key bindings  |
# +----------------+
# https://blog.quarticcat.com/zh/posts/how-do-i-make-my-zsh-smooth-as-fuck/#key-bindingszsh
bindkey -r '^['  # [Esc] (Default: vi-cmd-mode)
bindkey '^Z' undo         # [Ctrl-Z]
bindkey '^Y' redo         # [Ctrl-Y]
bindkey '^Q' push-line    # [Ctrl-Q]
bindkey ' '  magic-space  # [Space] Do history expansion. !! will print command at first but not execute directly

# +----------------+
# | other settings |
# +----------------+
# brew install without updating (https://github.com/Homebrew/brew/issues/1670)
export HOMEBREW_NO_AUTO_UPDATE=1
# thefuck
eval $(thefuck --alias)
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Load zshenv again to reoder PATH order messed by /etc/zprofile
source $DOTFILES_ZSH_HOME/zshenv
source $DOTFILES_ZSH_HOME/zle.zsh
source $DOTFILES_ZSH_HOME/alias.zsh
[[ -e $DOTFILES_ZSH_HOME/zshrc.local ]] && source $DOTFILES_ZSH_HOME/zshrc.local
eval "$(github-copilot-cli alias -- "$0")"
