# history
setopt SHARE_HISTORY  # adds history incrementally and share it across sessions
setopt EXTENDED_HISTORY # add timestamps to history
setopt HIST_IGNORE_ALL_DUPS # don't record duplicated commands in history
setopt HIST_REDUCE_BLANKS # Remove superfluous blanks from each command line being added to the history list.

source $DOTFILES_ZSH_HOME/appearance.zshrc
plugins=(osx zsh-syntax-highlighting zsh-autosuggestions autojump timer zsh-completions fzf-tab)
source $ZSH/oh-my-zsh.sh

# autoload loads script as function by searching $fpath.
# ref: https://coderwall.com/p/ktv3hq/zsh-autoloading-functions-i
# initialize autocomplete
autoload -U compinit
compinit -u  # -u to avoid security check

source $DOTFILES_ZSH_HOME/config.zshrc
source $DOTFILES_ZSH_HOME/zle.zshrc
source $DOTFILES_ZSH_HOME/alias.zshrc
[[ -e $DOTFILES_ZSH_HOME/zshrc.local ]] && source $DOTFILES_ZSH_HOME/zshrc.local

echo "Oh My Zsh!"  # Welcome
