[[manager.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on = "T"
run = "plugin hide-preview"
desc = "Hide or show preview"

[[manager.prepend_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[manager.prepend_keymap]]
on = "M"
run = "plugin max-preview"
desc = "Maximize or restore preview"

[[manager.prepend_keymap]]
on = ["b", "a"]
run = 'plugin mactag --args="add"'
desc = "Tag selected files"

[[manager.prepend_keymap]]
on = ["b", "r"]
run = 'plugin mactag --args="remove"'
desc = "Untag selected files"
