[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "<A-p>"
run = "plugin toggle-pane min-preview"
desc = "Show or hide preview"

[[mgr.prepend_keymap]]
on = "M"
run = "plugin toggle-pane max-preview"
desc = "Maximize preview"

[[mgr.pnd_keymap]]
on = "F"
run = "plugin smart-filter"
desc = "Smart filter"

[[mgr.prepend_keymap]]
on = ["b", "a"]
run = 'plugin mactag --args="add"'
desc = "Tag selected files"

[[mgr.prepend_keymap]]
on = ["b", "r"]
run = 'plugin mactag --args="remove"'
desc = "Untag selected files"
